### ISSUE TITLE
Code currently bugging on index.js:29:34

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [MadeByThePinsHub/RecapTime-ProbotApp#1]
```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.addLabels()". Use "issue_number" instead
    at Object.keys.forEach.key (/app/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26)
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as addLabels] (/app/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
at Command.commands [as callback] (/app/index.js:29:34)
    at Command.listener (/app/node_modules/probot-commands/index.js:17:19)
    at Application.<anonymous> (/app/node_modules/probot/lib/application.js:153:50)
    at step (/app/node_modules/probot/lib/application.js:43:23)
    at Object.next (/app/node_modules/probot/lib/application.js:24:53)
    at fulfilled (/app/node_modules/probot/lib/application.js:15:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) name: 'Deprecation' }
```

Currently, the bot is experiencing problems for now. The pasted log you see above tells what type of bug I'm experiencing.

**Comment by AndreiJirohHaliliDev2006** [comment]
Rewriting the whole code, preferred looking around the repo...

**Comment by AndreiJirohHaliliDev2006** [comment]
Problem solved. Any comments after this will be used as feedback on improving the codebase.
